import org.jetbrains.exposed.sql.Table

object Canciones: Table(){
    val id = integer("id").autoIncrement().primaryKey()
    val isFavorite = bool("Favorito")
    val year = varchar("year", length = 50)
    val country = varchar("country",length = 50)
    val region =varchar("region",length = 50)
    val artistName=varchar("artist name",length = 50)
    val song= varchar("song",length = 50)
    val artistGender=varchar("artist gender",length = 50)
    val groupOrSolo= varchar("group or solo",length = 50)
    val place = varchar("place", length = 50)
    val points= varchar("points", length = 50)
    val isFinal= varchar("is final", length = 50)
    val isSongInEnglish = varchar("song in english", length = 50)
    val songQuality= varchar("song quality",length = 50)
    val normalizedPoints= varchar("normalized points",length = 50)
    val energy= varchar("energy",length = 50)
    val duration= varchar("duration",length = 50)
    val acousticness= varchar("acousticness",length = 50)
    val danceability= varchar("danceability",length = 50)
    val tempo= varchar("tempo",length = 50)
    val speechiness=varchar("speechiness",length = 50)
    val key = varchar("key", length = 50)
    val liveness= varchar("liveness",length = 50)
    val timeSignature=varchar("Time Signature",length = 50)
    val mode = varchar("mode", length = 50)
    val loudness = varchar("loudness",length = 50)
    val valence = varchar("valence",length = 50)
    val happiness= varchar("hapiness",length = 50)
}